### ISSUE TITLE
Problema con date

### ISSUE THREAD

**Issue by guillermoprojaslema** [kattatzu/Sbif#2]
Estoy en un vista de blade de AdminLTE y quiero imprimir los datos del dólar por ejemplo

Esto funciona
```<h1> USD: {!! sbif_dollar('2017-07-20'); !!}</h1>```

pero esto no
```<h1> USD: {!! sbif_dollar(date('Y-m-d')) !!}</h1>```

Recibo como respuesta

```Client error: `GET http://api.sbif.cl/api-sbifv3/recursos_api/dolar/2017/07/dias/21?apikey=a7ef0bbe5600e2b74ea6e897a8b0e514baaf1eaf&formato=json` resulted in a `404 No Encontrado` response:
{
"CodigoHTTP": 404,
"CodigoError": 80,
"Mensaje": "No hay datos disponibles para los parametros ingresados"
}```

**Comment by kattatzu** [comment]
El problema es que estás consultando un fecha futura, al parecer no tienes definido el timezone en php o en laravel.

Implementaré un exception para capturar estas respuestas con error y otro para validar fechas futuras.

**Comment by kattatzu** [comment]
@guillermoprojaslema se agrega un exception para cuando se enviar una fecha futura y otro para capturar errores de conexión.

Saludos
