### ISSUE TITLE
Error en valor UF 

### ISSUE THREAD

**Issue by dfuentes141** [kattatzu/sbif#6]
Valor de la UF del día 11-04-2018 sale como 26.97 en lugar de ser 26.970, alguna forma para solucionar?

**Comment by pckz** [comment]
me acabo de dar cuenta del mismo error, 

los valores llegan así
**<Valor>5.435,28</Valor>**

y esta lib entrega: 
**5.435**

la razón es por esta función en Sbif.php (linea 313):
`private function normalizeNumber($number)
    {
        return (float)str_replace(",", ".", $number);
    }`

debería ser esta linea
`        return (float)str_replace(",", ".", str_replace(".", "", $number));
`

así, primero reemplazamos el punto (.) separador de miles por nada, y luego hacemos el reemplazo de la coma (,) por el punto (.) decimal

**Comment by kattatzu** [comment]
Hola,

esa corrección ya estaba en la función de normalización, pero para dejarlo mas claro lo dejé de esta forma:

private function normalizeNumber($number)
{
    $number = str_replace(".", "", $number);
    $number = str_replace(",", ".", $number);

    return (float)$number;
}

Saludos
